# Contributor Metrics

## Item Counts
the number of agents includes those how have only starred the repo - the number of actual active agents is 42

In [4]:
from kieker_analysis.queries.queries import Query
from kieker_analysis.sparql.client import run_dataframe
run_dataframe(Query.counts)

   agents  pullreqs  issues  commits  comments  reviews  r_reqs
0     137       742    2902     9131      6257      176     152

# User Activity
Here we look at user activity in terms of the metrics used in the Cheng Paper.
Note that ```closed_pull```, ```mention_issue_comments```, ```mention_pull_comments```, ```referred_issue_comments``` are all zero.

In [9]:
from kieker_analysis.stats.contributor_metrics import get_user_activity, metrics_all
metrics_all = metrics_all()
user_activity = get_user_activity(metrics_all)
user_activity

,closed_issue,closed_pull,commits_started,issue_comments,issues_opened,labels_issue,labels_pull,mention_issue_comments,mention_pull_comments,pr_comments,pull_reqs_opened,referred_issue_comments,referred_pull_comments
https://github.com/SoerenHenning,0,0,484,0,0,0,0,0,0,5,9,0,1
https://github.com/lbl-dev,0,0,74,0,0,0,0,0,0,0,7,0,0
https://github.com/Marcel-Ha,0,0,0,0,0,0,0,0,0,0,1,0,0
https://github.com/monperrus,0,0,1,0,0,0,0,0,0,1,2,0,0
https://github.com/whasselbring,0,0,2,0,0,0,0,0,0,0,2,0,0
https://github.com/sassanmo,0,0,15,0,0,0,0,0,0,0,0,0,0
https://github.com/duelle,0,0,222,0,0,0,12,0,0,37,73,0,0
https://github.com/ShaggsOn,0,0,11,0,0,0,0,0,0,0,0,0,0
https://github.com/dependabot%5Bbot%5D,0,0,212,0,0,0,0,0,0,0,0,0,0
https://github.com/Rackles,0,0,7,0,0,0,0,0,0,0,4,0,0
https://github.com/nexxTM,0,0,34,0,0,0,0,0,0,0,0,0,0
https://github.com/oleosterhagen,0,0,1,0,0,0,0,0,0,0,0,0,0
https://github.com/ChristianWulf,0,0,0,0,0,0,0,0,0,15,45,0,0
https://github.com/RvonMassow,0,0,19,0,0,0,0,0,0,0,0,0,0
https://github.com/Col20s,0,0,0,0,0,0,0,0,0,0,3,0,0
https://github.com/apps/dependabot,0,0,0,0,0,0,393,0,0,37,235,0,0
https://github.com/WassimDhib,0,0,0,0,0,0,0,0,0,0,0,0,1
https://github.com/kieker-ci,0,0,7,0,0,0,0,0,0,1,5,0,0
https://github.com/stro18,0,0,3,0,0,0,0,0,0,0,1,0,0
https://github.com/aaschmid,0,0,1,0,0,0,0,0,0,5,2,0,0
https://github.com/DaGeRe,1,0,550,2,8,0,0,0,0,50,97,0,0
https://github.com/madcau,0,0,0,0,0,0,0,0,0,1,5,0,0
https://github.com/nils,0,0,0,1,0,0,0,0,0,0,0,0,0
https://github.com/simontrapp,0,0,0,0,0,0,0,0,0,0,1,0,0
https://github.com/danishmanzoor,0,0,0,0,0,0,0,0,0,0,1,0,0
https://github.com/iaavo,0,0,2,0,0,0,0,0,0,0,1,0,0
https://github.com/shinhyungyang,0,0,17,1,0,0,0,0,0,9,4,0,3
https://github.com/JanWaller,0,0,993,0,0,0,0,0,0,0,0,0,0
https://github.com/cbkurz,0,0,1,0,0,0,0,0,0,1,1,0,0
https://github.com/reh2ur,0,0,1,0,0,0,0,0,0,0,0,0,0
https://github.com/avanhoorn,0,0,475,0,0,0,0,0,0,19,19,0,0
https://github.com/teeratpitakrat,0,0,98,0,0,0,0,0,0,0,0,0,0
https://github.com/DanielMSchmidt,0,0,0,0,0,0,0,0,0,2,2,0,0
https://github.com/ChristianStier,0,0,0,0,0,0,0,0,0,2,0,0,0
https://github.com/tfrotscher,0,0,11,0,0,0,0,0,0,0,0,0,0
https://github.com/holgerknoche,0,0,92,0,0,0,0,0,0,1,13,0,0
https://github.com/czirkelbach,0,0,0,0,0,0,0,0,0,0,1,0,0
https://github.com/marius,0,0,0,1,0,0,0,0,0,0,0,0,0
https://github.com/malte-hansen,0,0,0,0,0,0,0,0,0,2,0,0,0
https://github.com/jan,0,0,0,1,0,0,0,0,0,0,0,0,0
https://github.com/wds8237,0,0,0,0,0,0,0,0,0,1,1,0,0
https://github.com/rju,1452,0,131,6004,2152,1705,0,0,0,58,207,0,0

The user activities and counts present in Kieker are: